### ISSUE TITLE
question about your icons picker

### ISSUE THREAD

**Issue by designforwebsites** [kmhcreative/icon-picker#1]
hey 

First thanks for icon picker plugin it is awesome works like clock work. i am writing because i am web developer who is developing he's own wordpress theme but who hasn't come out of the closet yet with his ideas.  i am not hard coder with javascript(getting there) and thats why i am using your plugin. but lets get to the point. i want use your plugin but i have problem with that, i want to use that in my setting api page, i can get all buttons and so , but it not poping up. If it is under your plugin  settings -> icon picker example it works like charm, but when i move all code do my options pages its not working. I have included all files to folder and check the path ways and and plugin is checked as well but nothing. Maybe you can help me  .

Cheers web developer from closet

**Comment by kmhcreative** [comment]
Without being able to see your code I can only guess that maybe your theme isn't enqueuing the script properly, especially if you just copied the code directly, it will only enqueue on the sample plugin's options page (line 36 in the sample plugin).  Also, make sure you aren't trying to enqueue it from within the sample plugin - copy the entire icon-picker folder into your theme and point to it there.  But again, just guessing since I can't see your code.

Multiple instances of the icon-picker are used in my ZappBar plugin.  It might help you to look at the options page code for that.  You may also want to take a look at how Plethora Themes integrated the icon-picker code to their theme framework (click the number next to "Fork" at the top to go to their repo).

**Comment by designforwebsites** [comment]
Tnx for replay, sry yeah my mistake i didnt included most important part
the code. i didnt explained exactly what i wanted as well. I wanted to move
the code to another page. Your are using add_options_page hook but i used

##  add_theme_page

THE CODE:

// Make sure we only enqueue on our options page //
global $pagenow;
if ($pagenow=="options-general.php" && isset( $_GET['page'] ) &&
$_GET['page'] == 'maximus_settings'  ) {
add_action( 'admin_enqueue_scripts', 'icon_picker_scripts' );
}

---

i didnt know that if you are loading it from theme page you have to change
the url , where are options are loaded, i didnt change the
options-general.php to themes.php first, that way it was not working but
now it is working like charm. just getting know little bit more WP setting
API. But anyway thanks for the great plugin. Makes my developing much
easier.

Cheers

**Comment by kmhcreative** [comment]
You're welcome, glad it's useful to you and others.  Happy coding!
